name: breaking

on:
  pull_request:
  push:
    branches: [main]

jobs:
  buf-breaking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - run: buf breaking --against 'https://github.com/vellankikoti/kotg-schema.git#tag=v1.0.0'
