name: lint

on:
  pull_request:
  push:
    branches: [main]

jobs:
  buf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - run: buf lint
      - run: buf format --diff --exit-code

  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "stable"
      - run: go build ./...
      - run: go test ./... -count=1 -timeout=60s
      - uses: golangci/golangci-lint-action@v7
        with:
          version: v2.1.6
          args: --timeout=2m ./examples/...
